spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:cryptoDB

server:
  port: 8080
crypto:
  initial:
    data: classpath:initial_data

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:h2:mem:cryptoDB
    password: admin
    username: admin
server:
  port: 9000

---
logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: debug

spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  mvc:
    format:
      date: yyyy-MM-dd
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=2,expireAfterAccess=3600s

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: .*
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests. Rate-limit set to 1 per 3seconds\", \"message\": \"You have exhausted your API Request Quota\" }"
      rate-limits:
        - expression: "getRemoteAddr()"
          bandwidths:
            - capacity: 1
              time: 3
              unit: seconds


springdoc:
    api-docs:
      path: /api/v1/crypto/api-docs




