spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:cryptoDB

server:
  port: 8080
crypto:
  initial:
    data: classpath:initial_data

---
spring:
  profiles: prod
  datasource:
    url: jdbc:h2:mem:cryptoDB
    password: admin
    username: admin
server:
  port: 9000

---
logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: debug

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: none
  mvc:
    format:
      date: yyyy-MM-dd

springdoc:
    api-docs:
      path: /api/v1/crypto/api-docs




